FROM golang:1.24-bookworm AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/osix-k8s-operator ./cmd/osix-k8s-operator

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/osix-k8s-operator /usr/local/bin/osix-k8s-operator
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/osix-k8s-operator"]
