package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		fatal(err)
	}
	deployRoot := filepath.Join(repoRoot, "deploy", "kubernetes")
	resources, err := readResources(filepath.Join(deployRoot, "kustomization.yaml"))
	if err != nil {
		fatal(err)
	}
	var parts []string
	for _, resource := range resources {
		data, err := os.ReadFile(filepath.Join(deployRoot, filepath.FromSlash(resource)))
		if err != nil {
			fatal(err)
		}
		parts = append(parts, strings.TrimSpace(string(data)))
	}
	rendered := strings.Join(parts, "\n---\n") + "\n"
	source := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\n\npackage k8soperator\n\nconst renderedInstallManifests = %s\n", strconv.Quote(rendered))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fatal(err)
	}
	output := filepath.Join(repoRoot, "internal", "k8soperator", "manifests_generated.go")
	if err := os.WriteFile(output, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func readResources(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	scanner := bufio.NewScanner(bytes.NewReader(data))
	inResources := false
	var resources []string
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "resources:" {
			inResources = true
			continue
		}
		if !inResources {
			continue
		}
		if strings.HasPrefix(trimmed, "-") {
			resource := strings.TrimSpace(strings.TrimPrefix(trimmed, "-"))
			if resource != "" {
				resources = append(resources, resource)
			}
			continue
		}
		if trimmed != "" && !strings.HasPrefix(trimmed, "#") {
			break
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(resources) == 0 {
		return nil, fmt.Errorf("no resources found in %s", path)
	}
	return resources, nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
